// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohewljmokeyuohfjornq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oZXdsam1va2V5dW9oZmpvcm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MTk4NDQsImV4cCI6MjA2NTM5NTg0NH0.4lAikBDmemRiD9J3ndJzGNbdJuyk5aUqnOETsFnIjm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);